import {test,expect} from '@playwright/test';
test('慢模型等待可配置、审阅后只提交一次且保留既有预算',async({page})=>{
 await page.goto('/demo.html#settings');
 await page.getByRole('button',{name:'连接模型',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.locator('#model-endpoint').fill('https://example.invalid/v1/chat/completions');
 await dialog.locator('#model-name').fill('synthetic-model');
 await dialog.locator('input[type=password]').fill('SYNTHETIC_NO_NETWORK');
 await dialog.getByText('连接与等待时间',{exact:true}).click();
 await expect(dialog.getByLabel('整个请求时限秒数')).toHaveValue('30');
 await dialog.getByLabel('整个请求时限秒数').fill('600');
 await dialog.getByLabel('连接等待秒数').fill('121');
 await expect(dialog.getByRole('button',{name:'检查并继续'})).toBeDisabled();
 await dialog.getByLabel('连接等待秒数').fill('15');
 await dialog.getByLabel('单次读取等待秒数').fill('300');
 await dialog.getByRole('button',{name:'检查并继续'}).click();
 await expect(dialog).toContainText('连接 15 秒 / 读取 300 秒 / 整个请求 600 秒');
 await dialog.getByRole('checkbox').nth(0).check();await dialog.getByRole('checkbox').nth(1).check();
 await dialog.getByRole('button',{name:'保存授权并启动服务'}).click();
 await expect(dialog).toHaveCount(0);
 const calls=await page.evaluate(()=>(window as any).__DEMO_CALLS__.filter((x:any)=>x.command==='configure_memory_model'));
 expect(calls).toHaveLength(1);
 expect(calls[0].args.config.timeouts).toEqual({connect_seconds:15,read_seconds:300,operation_seconds:600});
 expect(calls[0].args.config.budget.max_calls_per_month).toBe(100);
 await page.getByRole('button',{name:'检查模型设置',exact:true}).click();
 await dialog.getByText('连接与等待时间',{exact:true}).click();
 await expect(dialog.getByLabel('整个请求时限秒数')).toHaveValue('600');
 await page.keyboard.press('Escape');
 expect(await page.evaluate(()=>(window as any).__DEMO_CALLS__.filter((x:any)=>x.command==='configure_memory_model').length)).toBe(1);
});
