import { useState } from 'react';
import type { ScopedService } from '../service/client';
import { appError, type AppError } from '../service/contracts';
import { scopeLabel, type BrowserRegistration, type ClientConfig } from '../service/types';
import { Badge, Dialog, ErrorNotice } from '../components/common';
import { Icon } from '../components/Icon';

export function ConnectionsPage({ service }: { service: ScopedService }) {
  const [setup, setSetup] = useState<'agent' | 'browser' | null>(null);
  const [agentConfigured, setAgentConfigured] = useState(false);
  const [browserConfigured, setBrowserConfigured] = useState(false);
  return <div className="standard-page connections-page"><div className="page-heading"><div><h1>把背景带到你使用的 AI</h1><p>连接当前空间，让客户端按需读取记忆和原始来源。</p></div></div><div className="scope-bar"><Icon name="shield" size={18} /><div><strong>{scopeLabel(service.scope)}</strong><span>连接仅授予这个范围。个人空间不会随项目自动共享。</span></div><Badge>本地连接</Badge></div><section className="connection-list" aria-label="客户端连接"><div className="connection-row"><span className="connection-logo agent-logo"><Icon name="code" size={26} /></span><div className="connection-info"><h2>本地 Agent <Badge tone={agentConfigured ? 'warning' : 'muted'}>{agentConfigured ? '配置已生成 · 未验证' : '尚未验证'}</Badge></h2><p>通过 MCP 读取稳定背景，并按需搜索、阅读与追溯来源。</p><div className="capability-list"><span>只读记忆</span><span>原文检索</span><span>来源追溯</span></div></div><button className="button" onClick={() => setSetup('agent')}>设置连接<Icon name="arrow" size={15} /></button></div><div className="connection-row"><span className="connection-logo browser-logo"><Icon name="globe" size={26} /></span><div className="connection-info"><h2>浏览器扩展 <Badge tone={browserConfigured ? 'warning' : 'muted'}>{browserConfigured ? '已注册 · 未验证' : '尚未验证'}</Badge></h2><p>在支持的网站中读取上下文、准备可见草稿。最后发送由你点击。</p><div className="capability-list"><span>本机桥接</span><span>范围授权</span><span>人工发送</span></div></div><button className="button" onClick={() => setSetup('browser')}>设置连接<Icon name="arrow" size={15} /></button></div></section><div className="section-heading connection-explainer"><h2>连接成功后，会发生什么</h2></div><div className="connection-steps"><div><span>01</span><h3>从稳定背景开始</h3><p>客户端读取当前空间的通用背景，避免每次重新介绍。</p></div><div><span>02</span><h3>需要时，查找细节</h3><p>客户端使用只读工具查询记忆与原话，不把所有历史塞进每次请求。</p></div><div><span>03</span><h3>每个结果都有出处</h3><p>回到来源核对；纠正与撤回后，新的读取遵循最新状态。</p></div></div><p className="coverage-note">本页不会把安装文件或生成配置当作连通证据。当前尚无可验证的宿主调用回执；请在相应客户端完成连接检查。</p>{setup && <ConnectionDialog service={service} kind={setup} close={() => setSetup(null)} configured={() => setup === 'agent' ? setAgentConfigured(true) : setBrowserConfigured(true)} />}</div>;
}
function ConnectionDialog({ service, kind, close, configured }: { service: ScopedService; kind: 'agent' | 'browser'; close: () => void; configured: () => void }) {
  const [config, setConfig] = useState<ClientConfig | null>(null);
  const [registration, setRegistration] = useState<BrowserRegistration | null>(null);
  const [extensionId, setExtensionId] = useState('');
  const [browser, setBrowser] = useState('chrome');
  const [capture, setCapture] = useState(false);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<AppError | null>(null);
  const prepare = async () => { if (busy) return; setBusy(true); setError(null); try { if (kind === 'agent') { setConfig(await service.clientConfig()); configured(); } else { const result = await service.browserConnection(extensionId, browser, capture); if (result) { setRegistration(result); configured(); } } } catch (reason) { setError(appError(reason)); } finally { setBusy(false); } };
  const copy = async () => { if (!config) return; setBusy(true); try { await service.copy(JSON.stringify(config, null, 2)); setCopied(true); } catch (reason) { setError(appError(reason)); } finally { setBusy(false); } };
  return <Dialog title={kind === 'agent' ? '连接本地 Agent' : '连接浏览器扩展'} close={close} busy={busy}><div className="modal-body">{error && <ErrorNotice error={error} />}<div className="scope-chip"><Icon name="shield" size={15} />只读范围：{scopeLabel(service.scope)}</div>{kind === 'agent' ? config ? <><p>配置已生成。将它添加到支持 MCP 的客户端，然后在客户端检查 RecallCard 的四个读取工具。</p><ol className="setup-steps"><li>打开客户端的 MCP 服务设置。</li><li>添加 RecallCard 本地服务配置。</li><li>检查 bootstrap、search、read、sources 的实际调用。</li></ol><details className="advanced-details"><summary>查看客户端配置</summary><pre>{JSON.stringify(config, null, 2)}</pre></details><p className="context-note">尚未收到宿主读取回执，当前不能确认已连接。</p></> : <><p>为当前资料范围生成本地 MCP 配置。不会自动修改其他应用的设置。</p><p className="muted">连接组件由完整 RecallCard 安装包提供。生成失败时会保留具体原因。</p></> : registration ? <><Badge tone="warning">已注册，等待浏览器检查</Badge><p>{registration.note}</p><p>回到 RecallCard 扩展，点击「检查连接」。确认实际读取成功后再使用。</p></> : <><p>先在浏览器安装 RecallCard 扩展，然后填写该扩展的 ID。注册前会显示系统确认。</p><label className="field-label" htmlFor="browser-kind">浏览器</label><select className="field-input" id="browser-kind" value={browser} onChange={event => setBrowser(event.target.value)}><option value="chrome">Chrome</option><option value="chromium">Chromium</option><option value="brave">Brave</option></select><label className="field-label" htmlFor="extension-id">RecallCard 扩展 ID</label><input id="extension-id" className="field-input" value={extensionId} onChange={event => setExtensionId(event.target.value.trim())} placeholder="浏览器扩展管理页中的 32 位 ID" autoComplete="off" spellCheck={false} /><label className="checkbox-row"><input type="checkbox" checked={capture} onChange={event => setCapture(event.target.checked)} />允许扩展保存经确认的对话到此范围</label><p className="context-note">此开关不代表自动捕获已实现。当前图形化注册支持 Linux。</p></>}</div><div className="modal-footer"><button className="button" onClick={close} disabled={busy}>{registration || config ? '完成' : '取消'}</button>{kind === 'agent' && config ? <button className="button primary" onClick={() => void copy()} disabled={busy}>{copied ? '已复制' : '复制客户端配置'}</button> : !registration && <button className="button primary" onClick={() => void prepare()} disabled={busy || kind === 'browser' && !/^[a-p]{32}$/.test(extensionId)}>{busy ? '正在处理…' : kind === 'agent' ? '生成本地配置' : '检查并注册连接'}</button>}</div></Dialog>;
}
