import { useState } from 'react';
import type { ScopedService } from '../service/client';
import type { AppError, JobStatus } from '../service/contracts';
import { useResource } from '../service/hooks';
import { dateLabel, platformLabel, type Conversation, type Message } from '../service/types';
import { Icon } from '../components/Icon';
import { Badge, EmptyState, ErrorNotice, Loading, Prose } from '../components/common';
import { JobRow } from '../components/Jobs';
import { navigate } from '../App';

export function SourcesPage({ service, selected, refresh, jobs, jobsError, importError, importing, importSources, reloadJobs }: { service: ScopedService; selected: string; refresh: number; jobs: JobStatus[]; jobsError: AppError | null; importError: AppError | null; importing: boolean; importSources: () => Promise<void>; reloadJobs: () => void }) {
  const [offset, setOffset] = useState(0);
  const [platform, setPlatform] = useState('all');
  const sources = useResource(() => service.conversations(offset), [service, offset, refresh]);
  const all = sources.data?.conversations || [];
  const rows = all.filter(row => platform === 'all' || row.platform === platform);
  const selectedSource = selected || rows[0]?.session_ref;
  const visibleJobs = jobs.filter(job => job.state !== 'completed' && job.state !== 'cancelled');
  const recentCompleted = jobs.find(job => job.state === 'completed');
  return <div className={`sources-layout ${selected ? 'has-selection' : ''}`}>
    {(importError || jobsError || visibleJobs.length > 0 || recentCompleted) && <section className="source-activity" aria-label="导入状态">{importError && <ErrorNotice error={importError} retry={() => void importSources()} />}{jobsError && <ErrorNotice error={jobsError} retry={reloadJobs} />}{visibleJobs.map(job => <JobRow key={job.job_id} job={job} service={service} refresh={reloadJobs} compact />)}{visibleJobs.length === 0 && recentCompleted && <div className="import-success"><Icon name="check" size={15} /><span>最近导入：新增 {recentCompleted.progress.events_added.toLocaleString()} 条消息，{recentCompleted.progress.events_duplicates.toLocaleString()} 条重复已跳过</span><button className="text-button" onClick={() => navigate('activity')}>查看记录</button></div>}</section>}
    <div className="split-view"><section className="collection-panel" aria-label="来源列表"><div className="collection-heading"><h1>来源</h1><span className="muted count-label">{sources.data ? `${sources.data.total} 段会话` : ''}</span></div><div className="collection-filter"><Icon name="globe" size={15} /><select aria-label="按来源平台筛选" value={platform} onChange={event => { setPlatform(event.target.value); navigate('sources'); }}><option value="all">全部平台</option>{[...new Set(all.map(row => row.platform))].map(name => <option key={name} value={name}>{platformLabel(name)}</option>)}</select><span>本页</span></div><div className="collection-scroll">{sources.loading ? <Loading /> : sources.error ? <ErrorNotice error={sources.error} retry={sources.refresh} /> : rows.length ? <div className="record-list">{rows.map(source => <SourceRow key={source.session_ref} source={source} selected={source.session_ref === selectedSource} />)}</div> : <div className="small-empty"><Icon name="sources" size={24} /><h3>还没有保存的来源</h3><p>用右上角「添加来源」导入官方导出。可以直接选择 ZIP，无需解压。</p></div>}</div><div className="pagination"><span>仅显示本机可访问的内容</span><div><button className="icon-button" aria-label="上一页来源" disabled={offset === 0 || sources.loading} onClick={() => setOffset(Math.max(0, offset - 50))}><Icon name="back" size={16} /></button><button className="icon-button" aria-label="下一页来源" disabled={sources.data?.next_offset == null || sources.loading} onClick={() => setOffset(sources.data!.next_offset!)}><Icon name="arrow" size={16} /></button></div></div></section><section className="reader-panel" aria-label="来源阅读区">{selectedSource ? <ConversationReader key={selectedSource} service={service} reference={selectedSource} refresh={refresh} /> : <EmptyState icon="sources" title="所有背景，都有来处"><p>导入 ChatGPT、DeepSeek 的官方导出文件。<br />保存后即可搜索原话，不必先等待记忆整理。</p><div className="supported-sources"><span>C<span>ChatGPT</span></span><span>D<span>DeepSeek</span></span><span><Icon name="file" size={17} /><span>JSON / ZIP</span></span></div></EmptyState>}</section></div>
  </div>;
}
function SourceRow({ source, selected }: { source: Conversation; selected: boolean }) {
  return <button className={`source-row ${selected ? 'selected' : ''}`} onClick={() => navigate('sources', source.session_ref)} aria-current={selected ? 'true' : undefined}><span className={`platform-icon ${source.platform.toLowerCase()}`}>{platformLabel(source.platform).slice(0, 1)}</span><div className="source-row-content"><div className="row-title">{source.title}</div><p>{platformLabel(source.platform)}<span>·</span>{source.message_count} 条消息</p><div className="row-meta"><span>已保存</span><span className="row-date">{dateLabel(source.captured_at)} 导入</span></div></div></button>;
}
function ConversationReader({ service, reference, refresh }: { service: ScopedService; reference: string; refresh: number }) {
  const [offset, setOffset] = useState(0);
  const conversation = useResource(() => service.messages(reference, offset), [service, reference, offset, refresh]);
  return <>{conversation.loading ? <Loading /> : conversation.error ? <ErrorNotice error={conversation.error} retry={conversation.refresh} /> : conversation.data && <><div className="reader-toolbar"><button className="text-button mobile-back" onClick={() => navigate('sources')}><Icon name="back" size={15} />来源列表</button><span className="reader-kind"><Icon name="sources" size={15} />{platformLabel(conversation.data.platform)}</span><Badge>已保存的原文</Badge></div><article className="conversation-article"><h1>{conversation.data.title}</h1><div className="article-byline"><span>{conversation.data.total} 条可访问消息</span><span>原始记录</span></div>{!conversation.data.order_known && <div className="context-note"><Icon name="alert" size={15} /><span>{conversation.data.order_kind === 'branch_forest' ? '此会话包含多个回答分支，以下按已保存的关系展示；不视为单一对话。' : '部分消息关系未知，以下为已保存的记录，不补写缺失内容。'}</span></div>}<div className="message-list">{conversation.data.messages.map(message => <MessageView key={message.ref} message={message} />)}</div><div className="reader-pagination"><button className="button compact" disabled={offset === 0} onClick={() => setOffset(0)}><Icon name="back" size={15} />回到开头</button><span>{offset + 1}–{offset + conversation.data.messages.length} / {conversation.data.total}</span><button className="button compact" disabled={conversation.data.next_offset === null} onClick={() => setOffset(conversation.data!.next_offset!)}>继续阅读<Icon name="arrow" size={15} /></button></div><p className="coverage-note">只包含已保存且当前可访问的内容。原始时间未知时，不用导入时间替代。</p></article></>}</>;
}
function MessageView({ message }: { message: Message }) {
  const role = message.role === 'user' ? '用户' : message.role === 'assistant' ? 'AI 助手' : message.role === 'tool' ? '工具' : '系统来源';
  return <section className="source-message">{message.branch?.gap_before && <div className="branch-marker">这里存在缺失的上文</div>}<header><span className={`role-avatar ${message.role}`}><Icon name={message.role === 'user' ? 'memory' : 'code'} size={14} /></span><strong>{role}</strong><span>{dateLabel(message.occurred_at, true)}</span>{message.branch?.child_count && message.branch.child_count > 1 ? <Badge tone="warning">分支点</Badge> : null}</header><Prose text={message.text} />{message.text_truncated && <p className="context-note">此条为节选，完整原文仍保存在本机文件中。</p>}{message.branch?.is_branch_end && <span className="branch-end">此分支末端</span>}</section>;
}
